# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

SECRET_TOKEN: 6839b52f69a104f3d952b712460b31e8ba46f777ae2812779f8ec5ebee7566894f8033d4e964a5cc90195d563987cbf97c6ff5d4804c8c7d2d67d6297235c490
STRIPE_PUBLISHABLE: pk_test_m0LPoPtchKWdXGRqWqa5mDer
STRIPE_SECRET: sk_test_7CzlvPICOEzD17yIdCEpQ9wA

production:
  SECRET_TOKEN: ENV['SECRET_TOKEN']

  STRIPE_PUBLISHABLE: ENV['STRIPE_PUBLISHABLE']
  STRIPE_SECRET: ENV['STRIPE_SECRET']

  AWS_ACCESS: ENV['AWS_ACCESS']
  AWS_ACCESS_SECRET: ENV['AWS_ACCESS_SECRET']
  AWS_BUCKET: ENV['AWS_BUCKET']

  MAILGUN_SMTP_PORT: ENV['MAILGUN_SMTP_PORT']
  MAILGUN_SMTP_SERVER: ENV['MAILGUN_SMTP_SERVER']
  MAILGUN_SMTP_LOGIN: ENV['MAILGUN_SMTP_LOGIN']
  MAILGUN_SMTP_PASSWORD: ENV['MAILGUN_SMTP_PASSWORD']
